### ISSUE TITLE
ERROR:sqlalchemy.pool.NullPool:Exception during reset or similar

### ISSUE THREAD

**Issue by rpappalax** [loads/loads-broker#46]
~~~

016-06-02 15:18:39,131][7132] Pruning 0 non-responding instances.
[2016-06-02 15:18:39,131][7132] Pulling base containers: heka
[2016-06-02 15:18:39,131][7132] Pulling base container images
ERROR:sqlalchemy.pool.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "/Users/rpappalardo/git/loads-broker4/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2574, in get_entry_map
    ep_map = self._ep_map
  File "/Users/rpappalardo/git/loads-broker4/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2545, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

**Comment by tarekziade** [comment]
We should be ok here now, reopen in case you get this again
